### ISSUE TITLE
should avoid duplicate db connection config code in __init__.py and views.py

### ISSUE THREAD

**Issue by Jelly-Yu** [tinyjumbo/stockweb#4]
#2 mentioned this.

**Comment by hyperchi** [comment]
@qiuzhihui  could you comment on this one and if you think this problem is solved just close it. or any following issues... just comment on this ticket.. So we can kinda have better idea about wht u r working on.. I am more of a jerk on style and framework. making sure everything's easier to maintain..

**Comment by qiuzhihui** [comment]
I've fixed this part.

**Comment by hyperchi** [comment]
@qiuzhihui  should actually mention how it is fixed...

**Comment by qiuzhihui** [comment]
I move the all DB parameter to config.py to maintain all the DB settings. And set up connection in the **inite** fuction in DBdriver.py DBdriver class.
